
name = "simpletinctures"
pages_build_output_dir = "site"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2026-08-01"
[[kv_namespaces]]
binding = "ST_TRACK"
id = "cecc1d99c58d4ef88d7542282f0cf603"
